[package]
name = "rusoto-dep-test"
version = "0.1.0"
authors = ["Benjamin Fry <benjaminfry@me.com>"]

[dependencies]
rusoto_core = { git = "https://github.com/bluejekyll/rusoto.git", branch = "bfry/move-cargo-toml" }

